
// Generated by generators/rootly/rootly.js
 
package rootly

import (
	
	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"github.com/rootlyhq/terraform-provider-rootly/v2/client"
	rootlygo "github.com/rootlyhq/terraform-provider-rootly/v2/schema"
)

type EscalationPolicyGenerator struct {
	RootlyService
}

func (g* EscalationPolicyGenerator) InitResources() error {
	page_size := 50
	page_num := 1

	client, err := g.RootlyClient()
	if err != nil {
		return err
	}

	for {
		resources, err := func(page_size, page_num int) ([]interface{}, error) {
			params := new(rootlygo.ListEscalationPoliciesParams)
			params.PageSize = &page_size
			params.PageNumber = &page_num
			return client.ListEscalationPolicies(params)
		}(page_size, page_num)

		if err != nil {
			return err
		}

		if len(resources) == 0 {
			break
		}

  	for _, resource := range resources {
      tf_resource := g.createEscalationPolicyResource(resource)
      g.Resources = append(g.Resources, tf_resource)
      child_escalation_level, err := g.createEscalationLevelResources(tf_resource.InstanceState.ID)
      if err != nil {
        return err
      }
      g.Resources = append(g.Resources, child_escalation_level...)
child_escalation_path, err := g.createEscalationPathResources(tf_resource.InstanceState.ID)
      if err != nil {
        return err
      }
      g.Resources = append(g.Resources, child_escalation_path...)
  	}

		page_num += 1
	}

	return nil
}

func (g *EscalationPolicyGenerator) createEscalationPolicyResource(provider_resource interface{}) terraformutils.Resource {
	x, _ := provider_resource.(*client.EscalationPolicy)
	return terraformutils.NewSimpleResource(
		x.ID,
		x.ID,
		"rootly_escalation_policy",
		g.ProviderName,
		[]string{},
	)
}


func (g *EscalationPolicyGenerator) PostConvertHook() error {
  for _, resource := range g.Resources {
		
    if resource.InstanceInfo.Type != "rootly_escalation_policy" {
      continue
    }
		
    
        for i, escalation_level := range g.Resources {
          if escalation_level.InstanceInfo.Type != "rootly_escalation_level" {
            continue
          }
          if escalation_level.InstanceState.Attributes["escalation_policy_id"] == resource.InstanceState.ID {
            g.Resources[i].Item["escalation_policy_id"] = "${" + resource.InstanceInfo.Type + "." + resource.ResourceName + ".id}"
          }
        }
      

        for i, escalation_path := range g.Resources {
          if escalation_path.InstanceInfo.Type != "rootly_escalation_path" {
            continue
          }
          if escalation_path.InstanceState.Attributes["escalation_policy_id"] == resource.InstanceState.ID {
            g.Resources[i].Item["escalation_policy_id"] = "${" + resource.InstanceInfo.Type + "." + resource.ResourceName + ".id}"
          }
        }
      
  }

  return nil
}


func (g *EscalationPolicyGenerator) createEscalationLevelResources(parent_id string) ([]terraformutils.Resource, error) {
	page_size := 50
	page_num := 1

	client, err := g.RootlyClient()
	if err != nil {
		return nil, err
	}

  var tf_resources []terraformutils.Resource

	for {
		resources, err := func(page_size, page_num int) ([]interface{}, error) {
			params := new(rootlygo.ListEscalationLevelsPoliciesParams)
			params.PageSize = &page_size
			params.PageNumber = &page_num
			return client.ListEscalationLevels(parent_id, params)
		}(page_size, page_num)

		if err != nil {
			return nil, err
		}

		if len(resources) == 0 {
			break
		}

  	for _, resource := range resources {
      tf_resources = append(tf_resources, g.createEscalationLevelResource(resource))
  	}

		page_num += 1
	}

	return tf_resources, nil
}

func (g *EscalationPolicyGenerator) createEscalationLevelResource(provider_resource interface{}) terraformutils.Resource {
	x, _ := provider_resource.(*client.EscalationLevel)
	return terraformutils.NewSimpleResource(
		x.ID,
		x.ID,
		"rootly_escalation_level",
		g.ProviderName,
		[]string{},
	)
}


func (g *EscalationPolicyGenerator) createEscalationPathResources(parent_id string) ([]terraformutils.Resource, error) {
	page_size := 50
	page_num := 1

	client, err := g.RootlyClient()
	if err != nil {
		return nil, err
	}

  var tf_resources []terraformutils.Resource

	for {
		resources, err := func(page_size, page_num int) ([]interface{}, error) {
			params := new(rootlygo.ListEscalationPathsParams)
			params.PageSize = &page_size
			params.PageNumber = &page_num
			return client.ListEscalationPaths(parent_id, params)
		}(page_size, page_num)

		if err != nil {
			return nil, err
		}

		if len(resources) == 0 {
			break
		}

  	for _, resource := range resources {
      tf_resources = append(tf_resources, g.createEscalationPathResource(resource))
  	}

		page_num += 1
	}

	return tf_resources, nil
}

func (g *EscalationPolicyGenerator) createEscalationPathResource(provider_resource interface{}) terraformutils.Resource {
	x, _ := provider_resource.(*client.EscalationPath)
	return terraformutils.NewSimpleResource(
		x.ID,
		x.ID,
		"rootly_escalation_path",
		g.ProviderName,
		[]string{},
	)
}

