
// Generated by generators/rootly/rootly.js
 
package rootly

import (
	
	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"github.com/rootlyhq/terraform-provider-rootly/v2/client"
	rootlygo "github.com/rootlyhq/terraform-provider-rootly/v2/schema"
)

type FormFieldGenerator struct {
	RootlyService
}

func (g* FormFieldGenerator) InitResources() error {
	page_size := 50
	page_num := 1

	client, err := g.RootlyClient()
	if err != nil {
		return err
	}

	for {
		resources, err := func(page_size, page_num int) ([]interface{}, error) {
			params := new(rootlygo.ListFormFieldsParams)
			params.PageSize = &page_size
			params.PageNumber = &page_num
			return client.ListFormFields(params)
		}(page_size, page_num)

		if err != nil {
			return err
		}

		if len(resources) == 0 {
			break
		}

  	for _, resource := range resources {
      tf_resource := g.createFormFieldResource(resource)
      g.Resources = append(g.Resources, tf_resource)
      child_form_field_option, err := g.createFormFieldOptionResources(tf_resource.InstanceState.ID)
      if err != nil {
        return err
      }
      g.Resources = append(g.Resources, child_form_field_option...)
child_form_field_placement, err := g.createFormFieldPlacementResources(tf_resource.InstanceState.ID)
      if err != nil {
        return err
      }
      g.Resources = append(g.Resources, child_form_field_placement...)
child_form_field_position, err := g.createFormFieldPositionResources(tf_resource.InstanceState.ID)
      if err != nil {
        return err
      }
      g.Resources = append(g.Resources, child_form_field_position...)
  	}

		page_num += 1
	}

	return nil
}

func (g *FormFieldGenerator) createFormFieldResource(provider_resource interface{}) terraformutils.Resource {
	x, _ := provider_resource.(*client.FormField)
	return terraformutils.NewSimpleResource(
		x.ID,
		x.Slug,
		"rootly_form_field",
		g.ProviderName,
		[]string{},
	)
}


func (g *FormFieldGenerator) PostConvertHook() error {
  for _, resource := range g.Resources {
		
    if resource.InstanceInfo.Type != "rootly_form_field" {
      continue
    }
		
    
        for i, form_field_option := range g.Resources {
          if form_field_option.InstanceInfo.Type != "rootly_form_field_option" {
            continue
          }
          if form_field_option.InstanceState.Attributes["form_field_id"] == resource.InstanceState.ID {
            g.Resources[i].Item["form_field_id"] = "${" + resource.InstanceInfo.Type + "." + resource.ResourceName + ".id}"
          }
        }
      

        for i, form_field_placement := range g.Resources {
          if form_field_placement.InstanceInfo.Type != "rootly_form_field_placement" {
            continue
          }
          if form_field_placement.InstanceState.Attributes["form_field_id"] == resource.InstanceState.ID {
            g.Resources[i].Item["form_field_id"] = "${" + resource.InstanceInfo.Type + "." + resource.ResourceName + ".id}"
          }
        }
      

        for i, form_field_position := range g.Resources {
          if form_field_position.InstanceInfo.Type != "rootly_form_field_position" {
            continue
          }
          if form_field_position.InstanceState.Attributes["form_field_id"] == resource.InstanceState.ID {
            g.Resources[i].Item["form_field_id"] = "${" + resource.InstanceInfo.Type + "." + resource.ResourceName + ".id}"
          }
        }
      
  }

  return nil
}


func (g *FormFieldGenerator) createFormFieldOptionResources(parent_id string) ([]terraformutils.Resource, error) {
	page_size := 50
	page_num := 1

	client, err := g.RootlyClient()
	if err != nil {
		return nil, err
	}

  var tf_resources []terraformutils.Resource

	for {
		resources, err := func(page_size, page_num int) ([]interface{}, error) {
			params := new(rootlygo.ListFormFieldOptionsParams)
			params.PageSize = &page_size
			params.PageNumber = &page_num
			return client.ListFormFieldOptions(parent_id, params)
		}(page_size, page_num)

		if err != nil {
			return nil, err
		}

		if len(resources) == 0 {
			break
		}

  	for _, resource := range resources {
      tf_resources = append(tf_resources, g.createFormFieldOptionResource(resource))
  	}

		page_num += 1
	}

	return tf_resources, nil
}

func (g *FormFieldGenerator) createFormFieldOptionResource(provider_resource interface{}) terraformutils.Resource {
	x, _ := provider_resource.(*client.FormFieldOption)
	return terraformutils.NewSimpleResource(
		x.ID,
		x.ID,
		"rootly_form_field_option",
		g.ProviderName,
		[]string{},
	)
}


func (g *FormFieldGenerator) createFormFieldPlacementResources(parent_id string) ([]terraformutils.Resource, error) {
	page_size := 50
	page_num := 1

	client, err := g.RootlyClient()
	if err != nil {
		return nil, err
	}

  var tf_resources []terraformutils.Resource

	for {
		resources, err := func(page_size, page_num int) ([]interface{}, error) {
			params := new(rootlygo.ListFormFieldPlacementsParams)
			params.PageSize = &page_size
			params.PageNumber = &page_num
			return client.ListFormFieldPlacements(parent_id, params)
		}(page_size, page_num)

		if err != nil {
			return nil, err
		}

		if len(resources) == 0 {
			break
		}

  	for _, resource := range resources {
      tf_resources = append(tf_resources, g.createFormFieldPlacementResource(resource))
  	}

		page_num += 1
	}

	return tf_resources, nil
}

func (g *FormFieldGenerator) createFormFieldPlacementResource(provider_resource interface{}) terraformutils.Resource {
	x, _ := provider_resource.(*client.FormFieldPlacement)
	return terraformutils.NewSimpleResource(
		x.ID,
		x.ID,
		"rootly_form_field_placement",
		g.ProviderName,
		[]string{},
	)
}


func (g *FormFieldGenerator) createFormFieldPositionResources(parent_id string) ([]terraformutils.Resource, error) {
	page_size := 50
	page_num := 1

	client, err := g.RootlyClient()
	if err != nil {
		return nil, err
	}

  var tf_resources []terraformutils.Resource

	for {
		resources, err := func(page_size, page_num int) ([]interface{}, error) {
			params := new(rootlygo.ListFormFieldPositionsParams)
			params.PageSize = &page_size
			params.PageNumber = &page_num
			return client.ListFormFieldPositions(parent_id, params)
		}(page_size, page_num)

		if err != nil {
			return nil, err
		}

		if len(resources) == 0 {
			break
		}

  	for _, resource := range resources {
      tf_resources = append(tf_resources, g.createFormFieldPositionResource(resource))
  	}

		page_num += 1
	}

	return tf_resources, nil
}

func (g *FormFieldGenerator) createFormFieldPositionResource(provider_resource interface{}) terraformutils.Resource {
	x, _ := provider_resource.(*client.FormFieldPosition)
	return terraformutils.NewSimpleResource(
		x.ID,
		x.ID,
		"rootly_form_field_position",
		g.ProviderName,
		[]string{},
	)
}

