
// Generated by generators/rootly/rootly.js
 
package rootly

import (
	
	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"github.com/rootlyhq/terraform-provider-rootly/v2/client"
	rootlygo "github.com/rootlyhq/terraform-provider-rootly/v2/schema"
)

type IncidentRoleGenerator struct {
	RootlyService
}

func (g* IncidentRoleGenerator) InitResources() error {
	page_size := 50
	page_num := 1

	client, err := g.RootlyClient()
	if err != nil {
		return err
	}

	for {
		resources, err := func(page_size, page_num int) ([]interface{}, error) {
			params := new(rootlygo.ListIncidentRolesParams)
			params.PageSize = &page_size
			params.PageNumber = &page_num
			return client.ListIncidentRoles(params)
		}(page_size, page_num)

		if err != nil {
			return err
		}

		if len(resources) == 0 {
			break
		}

  	for _, resource := range resources {
      tf_resource := g.createIncidentRoleResource(resource)
      g.Resources = append(g.Resources, tf_resource)
      child_incident_role_task, err := g.createIncidentRoleTaskResources(tf_resource.InstanceState.ID)
      if err != nil {
        return err
      }
      g.Resources = append(g.Resources, child_incident_role_task...)
  	}

		page_num += 1
	}

	return nil
}

func (g *IncidentRoleGenerator) createIncidentRoleResource(provider_resource interface{}) terraformutils.Resource {
	x, _ := provider_resource.(*client.IncidentRole)
	return terraformutils.NewSimpleResource(
		x.ID,
		x.Slug,
		"rootly_incident_role",
		g.ProviderName,
		[]string{},
	)
}


func (g *IncidentRoleGenerator) PostConvertHook() error {
  for _, resource := range g.Resources {
		
    if resource.InstanceInfo.Type != "rootly_incident_role" {
      continue
    }
		
    
        for i, incident_role_task := range g.Resources {
          if incident_role_task.InstanceInfo.Type != "rootly_incident_role_task" {
            continue
          }
          if incident_role_task.InstanceState.Attributes["incident_role_id"] == resource.InstanceState.ID {
            g.Resources[i].Item["incident_role_id"] = "${" + resource.InstanceInfo.Type + "." + resource.ResourceName + ".id}"
          }
        }
      
  }

  return nil
}


func (g *IncidentRoleGenerator) createIncidentRoleTaskResources(parent_id string) ([]terraformutils.Resource, error) {
	page_size := 50
	page_num := 1

	client, err := g.RootlyClient()
	if err != nil {
		return nil, err
	}

  var tf_resources []terraformutils.Resource

	for {
		resources, err := func(page_size, page_num int) ([]interface{}, error) {
			params := new(rootlygo.ListIncidentRoleTasksParams)
			params.PageSize = &page_size
			params.PageNumber = &page_num
			return client.ListIncidentRoleTasks(parent_id, params)
		}(page_size, page_num)

		if err != nil {
			return nil, err
		}

		if len(resources) == 0 {
			break
		}

  	for _, resource := range resources {
      tf_resources = append(tf_resources, g.createIncidentRoleTaskResource(resource))
  	}

		page_num += 1
	}

	return tf_resources, nil
}

func (g *IncidentRoleGenerator) createIncidentRoleTaskResource(provider_resource interface{}) terraformutils.Resource {
	x, _ := provider_resource.(*client.IncidentRoleTask)
	return terraformutils.NewSimpleResource(
		x.ID,
		x.ID,
		"rootly_incident_role_task",
		g.ProviderName,
		[]string{},
	)
}

