// Generated by generators/rootly/rootly.js
package rootly

import (
	"errors"
	"os"
	"github.com/zclconf/go-cty/cty"
	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
)

type RootlyProvider struct { //nolint
	terraformutils.Provider
	apiKey        string
	apiUrl        string
}

func (p *RootlyProvider) Init(args []string) error {
	if apiUrl := os.Getenv("ROOTLY_API_URL"); apiUrl != "" {
		p.apiUrl = os.Getenv("ROOTLY_API_URL")
	}
	if p.apiUrl == "" {
		p.apiUrl = "https://api.rootly.com"
	}

	if apiKey := os.Getenv("ROOTLY_API_TOKEN"); apiKey != "" {
		p.apiKey = os.Getenv("ROOTLY_API_TOKEN")
	}
	if args[0] != "" {
		p.apiKey = args[0]
	}
	if p.apiKey == "" {
		return errors.New("required API key missing")
	}

	return nil
}

func (p *RootlyProvider) InitService(serviceName string, verbose bool) error {
	var isSupported bool
	if _, isSupported = p.GetSupportedService()[serviceName]; !isSupported {
		return errors.New(p.GetName() + ": " + serviceName + " not supported service")
	}
	p.Service = p.GetSupportedService()[serviceName]
	p.Service.SetName(serviceName)
	p.Service.SetVerbose(verbose)
	p.Service.SetProviderName(p.GetName())
	// SetArgs are used for fetching details within other files in the terraformer code.
	p.Service.SetArgs(map[string]interface{}{
		"api_token": p.apiKey,
		"api_host":  p.apiUrl,
	})
	return nil
}

func (p *RootlyProvider) GetName() string {
	return "rootly"
}

func (p *RootlyProvider) GetSource() string {
	return "rootlyhq/rootly"
}

func (p *RootlyProvider) GetConfig() cty.Value {
	return cty.ObjectVal(map[string]cty.Value{
		"api_token": cty.StringVal(p.apiKey),
		"api_host":  cty.StringVal(p.apiUrl),
	})
}

func (p RootlyProvider) GetProviderData(arg ...string) map[string]interface{} {
	return map[string]interface{}{}
}

func (p *RootlyProvider) GetResourceConnections() map[string]map[string][]string {
	return map[string]map[string][]string{
		"rootly_playbook_task": {
					
							"rootly_playbook": {
								"playbook_id", "id",
							},
				},
    "rootly_incident_role_task": {
					
							"rootly_incident_role": {
								"incident_role_id", "id",
							},
				},
    "rootly_workflow_custom_field_selection": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
    "rootly_form_field_option": {
					
							"rootly_form_field": {
								"form_field_id", "id",
							},
				},
    "rootly_form_field_position": {
					
							"rootly_form_field": {
								"form_field_id", "id",
							},
				},
    "rootly_workflow_form_field_condition": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
    "rootly_workflow_task_add_action_item": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_action_item": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_add_role": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_add_slack_bookmark": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_add_team": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_add_to_timeline": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_archive_slack_channels": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_attach_datadog_dashboards": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_auto_assign_role_opsgenie": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_auto_assign_role_pagerduty": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_pagerduty_incident": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_pagertree_alert": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_pagertree_alert": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_auto_assign_role_victor_ops": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_call_people": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_airtable_table_record": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_asana_subtask": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_asana_task": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_confluence_page": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_datadog_notebook": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_dropbox_paper_page": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_github_issue": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_google_calendar_event": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_google_docs_page": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_google_calendar_event": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_google_docs_page": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_google_docs_permissions": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_remove_google_docs_permissions": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_quip_page": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_google_meeting": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_go_to_meeting": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_incident": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_incident_postmortem": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_jira_issue": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_jira_subtask": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_linear_issue": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_linear_subtask_issue": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_linear_issue_comment": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_microsoft_teams_meeting": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_notion_page": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_notion_page": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_service_now_incident": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_shortcut_story": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_shortcut_task": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_trello_card": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_webex_meeting": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_zendesk_ticket": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_clickup_task": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_zoom_meeting": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_get_github_commits": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_get_gitlab_commits": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_get_pulses": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_get_alerts": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_http_client": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_invite_to_slack_channel_opsgenie": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_invite_to_slack_channel_pagerduty": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_invite_to_slack_channel": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_invite_to_slack_channel_victor_ops": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_page_opsgenie_on_call_responders": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_opsgenie_alert": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_opsgenie_alert": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_opsgenie_incident": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_page_pagerduty_on_call_responders": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_page_victor_ops_on_call_responders": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_victor_ops_incident": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_print": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_publish_incident": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_redis_client": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_rename_slack_channel": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_run_command_heroku": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_send_email": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_send_dashboard_report": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_create_slack_channel": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_send_slack_message": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_send_sms": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_send_whatsapp_message": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_snapshot_datadog_graph": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_snapshot_grafana_dashboard": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_snapshot_looker_look": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_snapshot_new_relic_graph": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_tweet_twitter_message": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_airtable_table_record": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_asana_task": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_github_issue": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_incident": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_incident_postmortem": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_jira_issue": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_linear_issue": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_service_now_incident": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_shortcut_story": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_shortcut_task": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_slack_channel_topic": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_status": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_trello_card": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_clickup_task": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_update_zendesk_ticket": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_trigger_workflow": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
"rootly_workflow_task_send_slack_blocks": {
					
							"rootly_workflow_incident": {
								"workflow_id", "id",
							},

							"rootly_workflow_action_item": {
								"workflow_id", "id",
							},

							"rootly_workflow_post_mortem": {
								"workflow_id", "id",
							},

							"rootly_workflow_pulse": {
								"workflow_id", "id",
							},

							"rootly_workflow_alert": {
								"workflow_id", "id",
							},

							"rootly_workflow_simple": {
								"workflow_id", "id",
							},
				},
    "rootly_status_page_template": {
					
							"rootly_status_page": {
								"status_page_id", "id",
							},
				},
	}
}

func (p *RootlyProvider) GetSupportedService() map[string]terraformutils.ServiceGenerator {
	return map[string]terraformutils.ServiceGenerator{
		"environment": &EnvironmentGenerator{},
		"functionality": &FunctionalityGenerator{},
		"service": &ServiceGenerator{},
		"playbook": &PlaybookGenerator{},
		"cause": &CauseGenerator{},
		"severity": &SeverityGenerator{},
		"status_page": &StatusPageGenerator{},
		"incident_role": &IncidentRoleGenerator{},
		"post_mortem_template": &PostMortemTemplateGenerator{},
		"retrospective_step": &RetrospectiveStepGenerator{},
		"team": &TeamGenerator{},
		"incident_type": &IncidentTypeGenerator{},
		"workflow": &WorkflowGenerator{},
		"form_field": &FormFieldGenerator{},
		"workflow_group": &WorkflowGroupGenerator{},
		"dashboard": &DashboardGenerator{},
		"webhooks_endpoint": &WebhooksEndpointGenerator{},
		"secret": &SecretGenerator{},
	}
}
