
// Generated by generators/rootly/rootly.js
 
package rootly

import (
	
	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"github.com/rootlyhq/terraform-provider-rootly/v2/client"
	rootlygo "github.com/rootlyhq/terraform-provider-rootly/v2/schema"
)

type StatusPageGenerator struct {
	RootlyService
}

func (g* StatusPageGenerator) InitResources() error {
	page_size := 50
	page_num := 1

	client, err := g.RootlyClient()
	if err != nil {
		return err
	}

	for {
		resources, err := func(page_size, page_num int) ([]interface{}, error) {
			params := new(rootlygo.ListStatusPagesParams)
			params.PageSize = &page_size
			params.PageNumber = &page_num
			return client.ListStatusPages(params)
		}(page_size, page_num)

		if err != nil {
			return err
		}

		if len(resources) == 0 {
			break
		}

  	for _, resource := range resources {
      tf_resource := g.createStatusPageResource(resource)
      g.Resources = append(g.Resources, tf_resource)
      child_status_page_template, err := g.createStatusPageTemplateResources(tf_resource.InstanceState.ID)
      if err != nil {
        return err
      }
      g.Resources = append(g.Resources, child_status_page_template...)
  	}

		page_num += 1
	}

	return nil
}

func (g *StatusPageGenerator) createStatusPageResource(provider_resource interface{}) terraformutils.Resource {
	x, _ := provider_resource.(*client.StatusPage)
	return terraformutils.NewSimpleResource(
		x.ID,
		x.ID,
		"rootly_status_page",
		g.ProviderName,
		[]string{},
	)
}


func (g *StatusPageGenerator) PostConvertHook() error {
  for _, resource := range g.Resources {
		
    if resource.InstanceInfo.Type != "rootly_status_page" {
      continue
    }
		
    
        for i, status_page_template := range g.Resources {
          if status_page_template.InstanceInfo.Type != "rootly_status_page_template" {
            continue
          }
          if status_page_template.InstanceState.Attributes["status_page_id"] == resource.InstanceState.ID {
            g.Resources[i].Item["status_page_id"] = "${" + resource.InstanceInfo.Type + "." + resource.ResourceName + ".id}"
          }
        }
      
  }

  return nil
}


func (g *StatusPageGenerator) createStatusPageTemplateResources(parent_id string) ([]terraformutils.Resource, error) {
	page_size := 50
	page_num := 1

	client, err := g.RootlyClient()
	if err != nil {
		return nil, err
	}

  var tf_resources []terraformutils.Resource

	for {
		resources, err := func(page_size, page_num int) ([]interface{}, error) {
			params := new(rootlygo.ListStatusPageTemplatesParams)
			params.PageSize = &page_size
			params.PageNumber = &page_num
			return client.ListStatusPageTemplates(parent_id, params)
		}(page_size, page_num)

		if err != nil {
			return nil, err
		}

		if len(resources) == 0 {
			break
		}

  	for _, resource := range resources {
      tf_resources = append(tf_resources, g.createStatusPageTemplateResource(resource))
  	}

		page_num += 1
	}

	return tf_resources, nil
}

func (g *StatusPageGenerator) createStatusPageTemplateResource(provider_resource interface{}) terraformutils.Resource {
	x, _ := provider_resource.(*client.StatusPageTemplate)
	return terraformutils.NewSimpleResource(
		x.ID,
		x.ID,
		"rootly_status_page_template",
		g.ProviderName,
		[]string{},
	)
}

