
// Generated by generators/rootly/rootly.js
 
package rootly

import (
	
	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"github.com/rootlyhq/terraform-provider-rootly/v2/client"
	rootlygo "github.com/rootlyhq/terraform-provider-rootly/v2/schema"
)

type WorkflowGenerator struct {
	RootlyService
}

func (g* WorkflowGenerator) InitResources() error {
	page_size := 50
	page_num := 1

	client, err := g.RootlyClient()
	if err != nil {
		return err
	}

	for {
		resources, err := func(page_size, page_num int) ([]interface{}, error) {
			params := new(rootlygo.ListWorkflowsParams)
			params.PageSize = &page_size
			params.PageNumber = &page_num
			return client.ListWorkflows(params)
		}(page_size, page_num)

		if err != nil {
			return err
		}

		if len(resources) == 0 {
			break
		}

  	for _, resource := range resources {
      tf_resource := g.createWorkflowResource(resource)
      g.Resources = append(g.Resources, tf_resource)
      child_workflow_custom_field_selection, err := g.createWorkflowCustomFieldSelectionResources(tf_resource.InstanceState.ID)
      if err != nil {
        return err
      }
      g.Resources = append(g.Resources, child_workflow_custom_field_selection...)
child_workflow_form_field_condition, err := g.createWorkflowFormFieldConditionResources(tf_resource.InstanceState.ID)
      if err != nil {
        return err
      }
      g.Resources = append(g.Resources, child_workflow_form_field_condition...)
  	}

		page_num += 1
	}

	return nil
}

func (g *WorkflowGenerator) createWorkflowResource(provider_resource interface{}) terraformutils.Resource {
	x, _ := provider_resource.(*client.Workflow)
	return terraformutils.NewSimpleResource(
		x.ID,
		x.Slug,
		"rootly_workflow_" + x.TriggerParams["trigger_type"].(string),
		g.ProviderName,
		[]string{},
	)
}


func (g *WorkflowGenerator) PostConvertHook() error {
  for _, resource := range g.Resources {
		
    if resource.InstanceInfo.Type != "rootly_workflow_incident" && resource.InstanceInfo.Type != "rootly_workflow_action_item" && resource.InstanceInfo.Type != "rootly_workflow_post_mortem" && resource.InstanceInfo.Type != "rootly_workflow_pulse" && resource.InstanceInfo.Type != "rootly_workflow_alert" && resource.InstanceInfo.Type != "rootly_workflow_simple" {
      continue
    }
		
    
        for i, workflow_custom_field_selection := range g.Resources {
          if workflow_custom_field_selection.InstanceInfo.Type != "rootly_workflow_custom_field_selection" {
            continue
          }
          if workflow_custom_field_selection.InstanceState.Attributes["workflow_id"] == resource.InstanceState.ID {
            g.Resources[i].Item["workflow_id"] = "${" + resource.InstanceInfo.Type + "." + resource.ResourceName + ".id}"
          }
        }
      

        for i, workflow_form_field_condition := range g.Resources {
          if workflow_form_field_condition.InstanceInfo.Type != "rootly_workflow_form_field_condition" {
            continue
          }
          if workflow_form_field_condition.InstanceState.Attributes["workflow_id"] == resource.InstanceState.ID {
            g.Resources[i].Item["workflow_id"] = "${" + resource.InstanceInfo.Type + "." + resource.ResourceName + ".id}"
          }
        }
      
  }

  return nil
}


func (g *WorkflowGenerator) createWorkflowCustomFieldSelectionResources(parent_id string) ([]terraformutils.Resource, error) {
	page_size := 50
	page_num := 1

	client, err := g.RootlyClient()
	if err != nil {
		return nil, err
	}

  var tf_resources []terraformutils.Resource

	for {
		resources, err := func(page_size, page_num int) ([]interface{}, error) {
			params := new(rootlygo.ListWorkflowCustomFieldSelectionsParams)
			params.PageSize = &page_size
			params.PageNumber = &page_num
			return client.ListWorkflowCustomFieldSelections(parent_id, params)
		}(page_size, page_num)

		if err != nil {
			return nil, err
		}

		if len(resources) == 0 {
			break
		}

  	for _, resource := range resources {
      tf_resources = append(tf_resources, g.createWorkflowCustomFieldSelectionResource(resource))
  	}

		page_num += 1
	}

	return tf_resources, nil
}

func (g *WorkflowGenerator) createWorkflowCustomFieldSelectionResource(provider_resource interface{}) terraformutils.Resource {
	x, _ := provider_resource.(*client.WorkflowCustomFieldSelection)
	return terraformutils.NewSimpleResource(
		x.ID,
		x.ID,
		"rootly_workflow_custom_field_selection",
		g.ProviderName,
		[]string{},
	)
}


func (g *WorkflowGenerator) createWorkflowFormFieldConditionResources(parent_id string) ([]terraformutils.Resource, error) {
	page_size := 50
	page_num := 1

	client, err := g.RootlyClient()
	if err != nil {
		return nil, err
	}

  var tf_resources []terraformutils.Resource

	for {
		resources, err := func(page_size, page_num int) ([]interface{}, error) {
			params := new(rootlygo.ListWorkflowFormFieldConditionsParams)
			params.PageSize = &page_size
			params.PageNumber = &page_num
			return client.ListWorkflowFormFieldConditions(parent_id, params)
		}(page_size, page_num)

		if err != nil {
			return nil, err
		}

		if len(resources) == 0 {
			break
		}

  	for _, resource := range resources {
      tf_resources = append(tf_resources, g.createWorkflowFormFieldConditionResource(resource))
  	}

		page_num += 1
	}

	return tf_resources, nil
}

func (g *WorkflowGenerator) createWorkflowFormFieldConditionResource(provider_resource interface{}) terraformutils.Resource {
	x, _ := provider_resource.(*client.WorkflowFormFieldCondition)
	return terraformutils.NewSimpleResource(
		x.ID,
		x.ID,
		"rootly_workflow_form_field_condition",
		g.ProviderName,
		[]string{},
	)
}

