name: "release"
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build for linux/amd64
        run: go build -o terraformer-rootly-linux-amd64

      - name: Build for linux/arm64
        run: GOOS=linux GOARCH=arm64 go build -o terraformer-rootly-linux-arm64

      - name: Build for mac
        run: GOOS=darwin go build -o terraformer-rootly-darwin-amd64

      - name: Build for mac Apple Silicon
        run: GOOS=darwin GOARCH=arm64 go build -o terraformer-rootly-darwin-arm64

      - name: Build for windows/amd64
        run: GOOS=windows GOARCH=amd64 go build -o terraformer-rootly-windows-amd64.exe

      - name: Build for windows/arm64
        run: GOOS=windows GOARCH=arm64 go build -o terraformer-rootly-windows-arm64.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            terraformer-rootly-linux-amd64
            terraformer-rootly-linux-arm64
            terraformer-rootly-darwin-amd64
            terraformer-rootly-darwin-arm64
            terraformer-rootly-windows-amd64.exe
            terraformer-rootly-windows-arm64.exe
